[workspace]
members = ["image_calibrate"]
resolver = "2"

[workspace.dependencies]
nalgebra = "0.32.1"
plotters = "0.3.3"

[workspace.dependencies.bytemuck]
version = ">=1.15.0"
features = ["derive"]

[workspace.dependencies.wgpu]
version = ">=0.19"

[workspace.dependencies.image]
version = "0.25"
features = ["png"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[workspace.dependencies.serde_json]
version = "1.0.91"

[workspace.dependencies.geo-nd]
version = ">0.5.0"
path = "../../geo-nd-rs"

[workspace.dependencies.clap]
version = "4.5.2"
features = ["string"]

