use std::any;
use std::rc::Rc;

use anyhow::anyhow;
use thunderclap::{CmdDescriptor, CommandArgs, json};

use photogram::{Cip, NamedPoint, PointMapping};

use geo_nd::{Quaternion, Vector};

use ic_base::{Point2D, Point3D, Quat};
use ic_camera::{CameraInstance, CameraProjection, LensPolys};
use ic_image::{Image, ImageDrawable, ImageRgb8};
use ic_projections::{Cylinder, CylindricalProjection};
use ic_spherical_image::{ImageFileIndex, SphericalImage, SphericalImageShape};
use indexed::Idx;

use crate::Result;
use crate::cmd::{CmdArgs, CmdResult};

//a Help
//hi IMAGE_LONG_HELP
const IMAGE_LONG_HELP: &str = "\
Given a Named Point Set, from a camera (type, position/direction), and
a Point Mapping Set draw crosses on an image corresponding to the PMS
frame positions and the Named Point's model position mapped onto the
camera, and write out to a new image.

";

//hi IMAGE_PATCH_LONG_HELP
const IMAGE_PATCH_LONG_HELP: &str = "\
Extract a triangular patch from an image as if viewed straight on

";

//hi LOCATE_LONG_HELP
const LOCATE_LONG_HELP: &str = "\
Use the CIP's point mappings, for given mapped names points, to locate
the camera, given its focal length, etc.

Pairs of point mappings are chosen that provide good subtended viewing
angles, and that are (from the camera's perspecfive) more orthogonal
to each other, are generated.

For each pair of mappings a surface is generated in model space, where
if the camera were placed on that surface it would 'see' the pair of
mappings with the angle between them the same as is on the image.

The first surfaces is iterated over, to find the position where the
sum of the distances from the surface of the *other* pairs is
minimized. This provides the initial best location for the camera.

This position is then adjusted by small amounts, to reduce the total
error seen by *all* of the surfaces.

";

//hi ORIENT_LONG_HELP
const ORIENT_LONG_HELP: &str = "\
Use the CIP's point mappings, for given mapped names points, to orient
the camera, given its positions etc.

Pairs of point mappings are chosen that provide good subtended viewing
angles, and that are (from the camera's perspecfive) more orthogonal
to each other, are generated.

For each pair of mappings a camera orientation is determined, which
would (if the camera is perfectly positioned) map the two points to
their positions on the camera sensor. This yields an array of
orientations (as quaternions).

The array of orientations is averaged, to produce the camera
orientation.

";

//hi CREATE_RAYS_LONG_HELP
const CREATE_RAYS_LONG_HELP: &str = "\
This combines Named Point model positions, camera *orientation* and
PMS files, to determine rays from those model positions.

This takes the Point Mapping Set and a camera description and uses
only the orientation from that description.

For each Named Point that is mapped it casts a ray from the camera
through the frame to generate the direction of rays *relative* to the
camera orientation, then it applies the inverse camera rotation to get
the real world direction of the ray.

Given the Named Point's model position and world direction, it has a
Model-space ray for the named point.
";

//hi SHOW_RAYS_LONG_HELP
const SHOW_RAYS_LONG_HELP: &str = "\
Using the camera, for a subset of the point mapping set for the CIP
(specified by the named points), show rays either to or from the
camera.

The rays are generated in the appropriate direction, and their start
and end points (given the focus distance of the camera) are provided.
";

//hi COMBINE_RAYS_FROM_MODEL_LONG_HELP
const COMBINE_RAYS_FROM_MODEL_LONG_HELP: &str = "\
This combines a list of from-model rays from a JSON file and generates
a model-space best location of ray intersection.

The rays in the file are from different model points and the direction
thereof should have been generated by casting rays through a camera
frame and applying in reverse the camera orientation.

Real-world rays will not intersect precisely; there will be a point
that has the minimum square distance from all the rays, though. This
is the point generated.

Combining the rays from model produces a Camera JSON result (with an updated
direction, no change to orientation), but does not modify the camera
";

impl CmdArgs {
    fn cip_new_cmd(&mut self) -> CmdResult {
        let cip_name = self.get_string_arg(0).unwrap();
        if self.project.find_cip(&cip_name).is_some() {
            return Err(anyhow!(
                "Project already contains a CIP with name {cip_name}"
            ));
        }
        let mut cip = Cip::new(cip_name);
        if !self.read_img().is_empty() {
            cip.set_image_filename(&self.read_img()[0]);
        }
        cip.set_camera(self.camera.clone().into());
        let cip = cip.into();
        self.cip = Some(cip);
        self.project.add_cip(self.cip.as_ref().unwrap().clone());
        Self::cmd_ok()
    }

    fn cip_select_cmd(&mut self) -> CmdResult {
        let cip_name = self.get_string_arg(0).unwrap();
        let Some(cip) = self.project.find_cip(&cip_name) else {
            return Err(anyhow!(
                "Project does not contain a CIP with name {cip_name}"
            ));
        };
        self.cip = Some(cip.clone());
        Self::cmd_ok()
    }

    fn cip_as_json_cmd(self: &mut CmdArgs) -> CmdResult {
        self.validate_cip()?;
        Ok(json::to_value(
            self.cip().unwrap().borrow().to_json(self.pretty_json())?,
        )?)
    }
    fn cip_add_pm_cmd(&mut self) -> CmdResult {
        self.validate_cip()?;
        let np_name = self.get_string_arg(0).unwrap();
        let pxy = self.get_point2d(0).unwrap();
        let cip = self.cip.as_ref().unwrap().borrow_mut();
        let error = self.max_error();
        if cip.pms().borrow().mapping_of_np_name(np_name).is_some() {
            return Err(anyhow!("Mapping for '{np_name}' already exists in CIP"));
        }
        cip.pms_mut()
            .add_mapping(&self.nps.borrow(), np_name, pxy, error);
        Self::cmd_ok()
    }

    fn cip_orient_using_model_directions_cmd(&mut self) -> CmdResult {
        self.validate_cip()?;
        let nps = self.get_nps()?;
        let mut cip = self.cip.as_ref().unwrap().borrow_mut();
        fn filter(nps: &[Rc<NamedPoint>], pm: &PointMapping) -> bool {
            nps.iter().any(|np| pm.is_mapping_of_np(np))
        }
        cip.orient_camera_using_model_directions(|_, pm| filter(&nps, pm))?;
        Self::cmd_ok()
    }

    fn cip_dx2_dy2_cmd(&mut self) -> CmdResult {
        self.validate_cip()?;
        let nps = self.get_nps()?;
        let mut cip = self.cip.as_ref().unwrap().borrow();
        fn filter(nps: &[Rc<NamedPoint>], pm: &PointMapping) -> bool {
            nps.iter().any(|np| pm.is_mapping_of_np(np))
        }
        let dx2_dy2 = cip.dx2_dy2_of_camera(|_, pm| filter(&nps, pm));
        Ok(json::to_value(dx2_dy2)?)
    }

    const CIP_NEW_CMD: CmdDescriptor<Self> = CmdDescriptor::new("new")
        .about("Add a new CIP of a given name")
        .args(&[Self::ARG_POSITIONAL_NAME, Self::ARG_IMAGE_OPTIONAL])
        .handler(&Self::cip_new_cmd);

    const CIP_SELECT_CMD: CmdDescriptor<Self> = CmdDescriptor::new("select")
        .about("Select a CIP for adding points, orientation, etc")
        .args(&[Self::ARG_POSITIONAL_NAME])
        .handler(&Self::cip_select_cmd);

    const CIP_AS_JSON_CMD: CmdDescriptor<Self> = CmdDescriptor::new("as_json")
        .about("Generate the JSON for the current CIP")
        .args(&[])
        .handler(&Self::cip_as_json_cmd);

    const CIP_ADD_PM_CMD: CmdDescriptor<Self> = CmdDescriptor::new("add_pm")
        .about("Add a new point mapping for a known named-point to the current CIP")
        .args(&[
            Self::ARG_POSITIONAL_NAME,
            Self::ARG_ADD_XY_ONE,
            Self::ARG_MAX_ERROR,
        ])
        .handler(&Self::cip_add_pm_cmd);

    const CIP_ORIENT_USING_MODEL_DIRECTIONS_CMD: CmdDescriptor<Self> = CmdDescriptor::new(
        "orient_using_model_directions",
    )
    .about(
        "Change the camera for the CIP to orient such that the model *directions* are mapped well",
    )
    .args(&[Self::ARG_ADD_NAMED_POINT])
    .handler(&Self::cip_orient_using_model_directions_cmd);

    const CIP_DX2_DY2_CMD: CmdDescriptor<Self> = CmdDescriptor::new("dx2_dy2")
        .about("Calculate the total sensor dx_sq and dy_sq values for all the mapped points")
        .args(&[Self::ARG_ADD_NAMED_POINT])
        .handler(&Self::cip_dx2_dy2_cmd);

    pub(crate) const CIP_CMD: CmdDescriptor<Self> = CmdDescriptor::new("cip")
        .about("List, modify, interrogate etc a Camera/image/point-mapping-set")
        // .long_about(PROJECT_LONG_HELP)
        .args(&[])
        .cmds(&[
            Self::CIP_NEW_CMD,
            Self::CIP_SELECT_CMD,
            Self::CIP_AS_JSON_CMD,
            Self::CIP_ADD_PM_CMD,
            Self::CIP_ORIENT_USING_MODEL_DIRECTIONS_CMD,
            Self::CIP_DX2_DY2_CMD,
        ]);

    /*
        build.add_subcommand(as_json_cmd());
        build.add_subcommand(image_cmd());
        build.add_subcommand(image_patch_cmd());
        build.add_subcommand(show_mappings_cmd());
        build.add_subcommand(list_cmd());
        build.add_subcommand(add_cmd());
        build.add_subcommand(locate_cmd());
        build.add_subcommand(orient_cmd());
        build.add_subcommand(locate_and_orient_cmd());
        build.add_subcommand(relocate_and_orient_cmd());
        build.add_subcommand(create_rays_cmd());
        build.add_subcommand(combine_rays_from_model_cmd());
        build.add_subcommand(show_rays_cmd());
    */
}

/*
cip new 32 --image ${JPEG_DIR}/145A4632.JPG
cip add_pm LTvCloseTL 4475 4716

fn cip_locate_cmd(&mut self) -> CmdResult {
    self.validate_cip();
    let cip = self.cip().unwrap();

    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let n = pms_n.len();
    if n < 3 {
        return Err(format!("Required at least 3 mapped points, but found {n}",).into());
    }

    let max_pairs = cmd_args.max_pairs();
    let max_np_error = cmd_args.max_error();

    let filter = |n, pm: &PointMapping| {
        pm.named_point().is_mapped() && pms_n.contains(&n) && pm.model_uncertainty() < max_np_error
    };
    cmd_args
        .cip()
        .unwrap()
        .borrow_mut()
        .locate(filter, max_pairs)?;

    let camera = cmd_args.cip().unwrap().borrow().camera().borrow().clone();
    *cmd_args.camera_mut() = camera;
    cmd_args.if_verbose(|| {
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs()?;
    cmd_args.output_camera()
}

fn orient_fn(&mut self) -> CmdResult {
    if cmd_args.cip().is_none() {
        return Err("No CIP selected".to_string().into());
    }

    let pms_n = cmd_args.get_pms_indices_of_nps()?;

    let max_np_error = cmd_args.max_error();

    let filter = |n, pm: &PointMapping| pms_n.contains(&n) && pm.model_uncertainty() < max_np_error;
    let _total_error = cmd_args
        .cip()
        .unwrap()
        .borrow_mut()
        .orient_camera_using_model_directions(filter)?;

    let camera = cmd_args.cip().unwrap().borrow().camera().borrow().clone();
    *cmd_args.camera_mut() = camera;
    cmd_args.if_verbose(|| {
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs()?;
    cmd_args.output_camera()
}

fn locate_and_orient_fn(&mut self) -> CmdResult {
    if cmd_args.cip().is_none() {
        return Err("No CIP selected".to_string().into());
    }

    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let n = pms_n.len();
    if n < 3 {
        return Err(format!("Required at least 3 mapped points, but found {n}",).into());
    }

    let max_pairs = cmd_args.max_pairs();
    let max_np_error = cmd_args.max_error();
    let max_angle_subtended_error = 0.01;

    let camera = cmd_args.cip().unwrap().borrow().camera().borrow().clone();
    let filter = |n, pm: &PointMapping| pms_n.contains(&n) && pm.model_uncertainty() < max_np_error;
    let (err, camera) = cmd_args
        .cip()
        .unwrap()
        .borrow()
        .pms()
        .borrow_mut()
        .locate_and_orient(camera.clone(), filter, max_pairs, max_angle_subtended_error)?;

    cmd_args
        .cip()
        .unwrap()
        .borrow_mut()
        .set_camera(camera.clone().into());
    *cmd_args.camera_mut() = camera;
    cmd_args.if_verbose(|| {
        eprintln!("Eventual qr err {}", err);
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs()?;
    cmd_args.output_camera()
}

fn relocate_and_orient_fn(&mut self) -> CmdResult {
    if cmd_args.cip().is_none() {
        return Err("No CIP selected".to_string().into());
    }

    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let n = pms_n.len();
    if n < 3 {
        return Err(format!("Required at least 3 mapped points, but found {n}",).into());
    }

    let max_np_error = cmd_args.max_error();
    let range = cmd_args.range();
    let steps = cmd_args.steps();

    let camera = cmd_args.cip().unwrap().borrow().camera().borrow().clone();
    let filter = |n, pm: &PointMapping| pms_n.contains(&n) && pm.model_uncertainty() < max_np_error;
    let (err, camera) = cmd_args
        .cip()
        .unwrap()
        .borrow()
        .pms()
        .borrow_mut()
        .relocate_and_orient(camera.clone(), filter, range, steps)?;

    cmd_args
        .cip()
        .unwrap()
        .borrow_mut()
        .set_camera(camera.clone().into());
    *cmd_args.camera_mut() = camera;
    cmd_args.if_verbose(|| {
        eprintln!("Eventual qr err {}", err);
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs()?;
    cmd_args.output_camera()
}

fn image_fn(&mut self) -> CmdResult {
    let nps_n = cmd_args.get_nps()?;
    let pms_n = cmd_args.get_pms_indices_of_nps()?;

    let pms_color = cmd_args.pms_color();
    let model_color = cmd_args.model_color();
    let use_nps_colors = cmd_args.pms_color().is_none() && cmd_args.model_color().is_none();

    let write_filename = cmd_args.write_img().unwrap();

    let mut img = cmd_args.get_image_read_or_create()?;

    let c = [255, 255, 255, 255].into();
    let cn = [255, 190, 190, 255].into();
    let camera = cmd_args.camera();
    for i in 0_usize..200 {
        let xyz = (i as f64) * 1.0;
        let sz = {
            if i.is_multiple_of(10) {
                3.0
            } else if i.is_multiple_of(5) {
                2.0
            } else {
                1.0
            }
        };
        let mapped = camera.world_xyz_to_px_abs_xy(&[xyz, 0., 0.].into());
        img.draw_cross(&mapped, sz, &c);
        let mapped = camera.world_xyz_to_px_abs_xy(&[0., xyz, 0.].into());
        img.draw_cross(&mapped, sz, &c);
        let mapped = camera.world_xyz_to_px_abs_xy(&[0., 0., xyz].into());
        img.draw_cross(&mapped, sz, &c);

        let mapped = camera.world_xyz_to_px_abs_xy(&[-xyz, 0., 0.].into());
        img.draw_cross(&mapped, sz, &cn);
        let mapped = camera.world_xyz_to_px_abs_xy(&[0., -xyz, 0.].into());
        img.draw_cross(&mapped, sz, &cn);
        let mapped = camera.world_xyz_to_px_abs_xy(&[0., 0., -xyz].into());
        img.draw_cross(&mapped, sz, &cn);
    }

    if pms_color.is_some() || use_nps_colors {
        cmd_args.pms_map(|pms| {
            let mappings = pms.mappings();
            for i in pms_n.iter() {
                let m = &mappings[*i];
                let c = pms_color.copied().unwrap_or(m.named_point().color());
                img.draw_cross(m.screen(), m.error(), &c);
            }
            Ok(())
        })?;
    }
    if model_color.is_some() || use_nps_colors {
        let camera = cmd_args.camera();
        for p in nps_n {
            let c = model_color.copied().unwrap_or(p.color());
            let xyz = p.model_pt();
            let n = (xyz[2] * 2.0).abs().floor() as usize;
            let dz = xyz[2].signum() / 2.0;
            for z in 0..n {
                let sz = {
                    if z.is_multiple_of(10) {
                        3.0
                    } else if z.is_multiple_of(5) {
                        2.0
                    } else {
                        1.0
                    }
                };
                let xyz = [xyz[0], xyz[1], (z as f64) * dz].into();
                let mapped = camera.world_xyz_to_px_abs_xy(&xyz);
                img.draw_cross(&mapped, sz, &c);
            }
            if xyz[0].abs() < xyz[1].abs() {
                let n = (xyz[0] * 2.0).abs().floor() as usize;
                let dx = xyz[0].signum() / 2.0;
                for x in 0..n {
                    let sz = {
                        if x.is_multiple_of(10) {
                            3.0
                        } else if x.is_multiple_of(5) {
                            2.0
                        } else {
                            1.0
                        }
                    };
                    let xyz = [(x as f64) * dx, xyz[1], 0.].into();
                    let mapped = camera.world_xyz_to_px_abs_xy(&xyz);
                    img.draw_cross(&mapped, sz, &c);
                }
            } else {
                let n = (xyz[1] * 2.0).abs().floor() as usize;
                let dy = xyz[1].signum() / 2.0;
                for y in 0..n {
                    let sz = {
                        if y.is_multiple_of(10) {
                            3.0
                        } else if y.is_multiple_of(5) {
                            2.0
                        } else {
                            1.0
                        }
                    };
                    let xyz = [xyz[0], (y as f64) * dy, 0.].into();
                    let mapped = camera.world_xyz_to_px_abs_xy(&xyz);
                    img.draw_cross(&mapped, sz, &c);
                }
            }
            let mapped = camera.world_xyz_to_px_abs_xy(&xyz);
            img.draw_cross(&mapped, 5.0, &c);
        }
    }
    img.write(write_filename)?;

    CmdArgs::cmd_ok()
}

fn image_patch_fn(&mut self) -> CmdResult {
    if cmd_args.cip().is_none() {
        return Err("No CIP selected".to_string().into());
    }

    let nps = cmd_args.get_nps()?;

    if nps.len() < 3 {
        return Err(format!("Need at least 3 points for a patch, got {}", nps.len()).into());
    }

    let cip = cmd_args.cip().unwrap().borrow();
    let camera = cip.camera_ref();

    let src_img = cmd_args.get_image_read_or_create()?;
    let write_filename = cmd_args.write_img().unwrap();

    let Some(mut patch) = ic_mapping::Patch::create(nps.iter().cloned()) else {
        return Err(format!("Failed to create patch for nps with {} points", nps.len()).into());
    };
    patch.set_render_px_per_model(25.0);
    patch.set_expansion_factor(1.1);
    patch.update_data();

    let patch_img = patch.create_img(&*camera, &src_img).unwrap();
    patch_img.write(write_filename)?;

    CmdArgs::cmd_ok()
}

fn show_rays_fn(&mut self) -> CmdResult {
    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let pms = cmd_args.pms();
    let camera = cmd_args.camera();

    let from_camera = false;
    for (_, (pm, ray)) in pms
        .borrow()
        .iter_mapped_rays(camera, from_camera)
        .enumerate()
        .filter(|(n, _pms_ray)| pms_n.contains(n))
    {
        let end = ray.start() + ray.direction() * camera.focus_distance();
        eprintln!("{} {end}", pm.named_point().ref_tag());
    }

    CmdArgs::cmd_ok()
}

fn create_rays_fn(&mut self) -> CmdResult {
    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let pms = cmd_args.pms();
    let camera = cmd_args.camera();
    let from_camera = cmd_args.from_camera();

    let named_rays: Vec<(String, Ray)> = pms
        .borrow()
        .iter_mapped_rays(camera, from_camera)
        .enumerate()
        .filter(|(n, _pm_ray)| pms_n.contains(n))
        .map(|(_, (pm, ray))| (pm.named_point().ref_tag().as_str().to_owned(), ray))
        .collect();
    let named_rays: NamedRayList = named_rays.into();
    named_rays.to_json(cmd_args.pretty_json())
}

fn combine_rays_from_model_fn(&mut self) -> CmdResult {
    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let pms = cmd_args.pms();
    let camera = cmd_args.camera().clone();
    let named_rays: Vec<(String, Ray)> = pms
        .borrow()
        .iter_mapped_rays(&camera, false)
        .enumerate()
        .filter(|(n, _pm_ray)| pms_n.contains(n))
        .map(|(_, (pm, ray))| (pm.named_point().ref_tag().as_str().to_owned(), ray))
        .collect();

    if named_rays.len() < 2 {
        return Err(format!(
            "Not enough rays ({}) to combine to generate a position for the camera",
            named_rays.len()
        )
        .into());
    }

    let position =
        Ray::closest_point(named_rays.iter().map(|(_, r)| r), &|r| 1.0 / r.tan_error()).unwrap();
    eprintln!("The rays from the model converge at the camera focal point at {position}",);

    let mut tot_d_sq = 0.0;
    for (_name, ray) in named_rays.iter() {
        let (_k, d_sq) = ray.distances(&position);
        cmd_args.if_verbose(|| {
            eprintln!("{}: k {} dsq {} d {}", _name, _k, d_sq, d_sq.sqrt());
        });
        tot_d_sq += d_sq;
    }

    eprintln!("Total dsq {tot_d_sq}");

    let mut camera = cmd_args.camera().clone();
    camera.set_position(&position);
    *cmd_args.camera_mut() = camera;
    cmd_args.if_verbose(|| {
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs()?;
    cmd_args.output_camera()
}

fn as_json_fn(&mut self) -> CmdResult {
    if cmd_args.cip().is_none() {
        return Err("No CIP selected".to_string().into());
    }

    cmd_args
        .cip()
        .unwrap()
        .borrow()
        .to_json(cmd_args.pretty_json())
}

fn show_mappings_fn(&mut self) -> CmdResult {
    let pms = cmd_args.pms().borrow();
    let nps = cmd_args.nps();
    let camera = cmd_args.camera();

    for pm in pms.mappings() {
        pm.show_mapped_error(camera);
    }
    nps.borrow().show_mappings(camera);

    let te = pms.total_error(camera);
    let we = pms.find_worst_error(camera).1;
    println!("WE {we:.2} TE {te:.2}");

    CmdArgs::cmd_ok()
}

fn list_fn(&mut self) -> CmdResult {
    let pms_n = cmd_args.get_pms_indices_of_nps()?;
    let pms = cmd_args.pms().borrow();
    let mappings = pms.mappings();

    for i in pms_n {
        let m = &mappings[i];
        if m.named_point().is_unmapped() {
            println!(
                "{} : <unmapped> -> [{:.1}, {:.1}] @ {:.1}",
                m.named_point().ref_tag(),
                m.screen()[0],
                m.screen()[1],
                m.error()
            );
        } else {
            println!(
                "{} : {} -> [{:.1}, {:.1}] @ {:.1}",
                m.named_point().ref_tag(),
                m.model(),
                m.screen()[0],
                m.screen()[1],
                m.error()
            );
        }
    }
    CmdArgs::cmd_ok()
}

fn locate_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("locate")
        .about("Find location and orientation for a camera to map points to model")
        .long_about(LOCATE_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, locate_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));
    CmdArgs::add_arg_max_pairs(&mut build, Some("100"));
    CmdArgs::add_arg_max_error(&mut build, Some("10.0"));

    build
}

fn orient_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("orient")
        .about("Set the orientation for a camera using weighted average of pairs of point mappings")
        .long_about(ORIENT_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, orient_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));
    CmdArgs::add_arg_max_error(&mut build, Some("10.0"));

    build
}

fn locate_and_orient_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("locate_and_orient")
        .about("Set the locate_and_orientation for a camera using weighted average of pairs of point mappings")
        .long_about(ORIENT_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, locate_and_orient_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));
    CmdArgs::add_arg_max_pairs(&mut build, Some("100"));
    CmdArgs::add_arg_max_error(&mut build, Some("10.0"));

    build
}

fn relocate_and_orient_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("relocate_and_orient")
        .about("Set the relocate_and_orientation for a camera using weighted average of pairs of point mappings")
        .long_about(ORIENT_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, relocate_and_orient_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));
    CmdArgs::add_arg_max_error(&mut build, Some("10.0"));
    CmdArgs::add_arg_steps(&mut build, Some("40"));
    CmdArgs::add_arg_range(&mut build, Some("10.0"));

    build
}

fn image_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("image")
        .about("Read image and draw crosses on named and mapped points")
        .long_about(IMAGE_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, image_fn);

    CmdArgs::add_arg_named_point(&mut build, (0,));
    CmdArgs::add_arg_pms(&mut build);

    CmdArgs::add_arg_read_image(&mut build, Some(1_usize)); // 0 or 1 in a list
    CmdArgs::add_arg_write_image(&mut build, true);

    CmdArgs::add_arg_pms_color(&mut build);
    CmdArgs::add_arg_model_color(&mut build);
    build
}

fn image_patch_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("image_patch")
        .about("Extract a patch from an image")
        .long_about(IMAGE_PATCH_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, image_patch_fn);

    // let cmd = cmdline_args::add_image_dir_arg(cmd, false);
    CmdArgs::add_arg_read_image(&mut build, 1_usize);
    CmdArgs::add_arg_write_image(&mut build, true);
    CmdArgs::add_arg_named_point(&mut build, (None, true));
    build
}

fn show_rays_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("show_rays")
        .about("Show rays for the CIP using its camera and mappings")
        .long_about(SHOW_RAYS_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, show_rays_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));

    // from_camera

    build
}

fn create_rays_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("create_rays")
        .about("Create rays for a given located camera and its mappings")
        .long_about(CREATE_RAYS_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, create_rays_fn);
    CmdArgs::add_arg_named_point(&mut build, (None, true));
    CmdArgs::add_arg_from_camera(&mut build);

    build
}

fn combine_rays_from_model_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("combine_rays_from_model")
        .about("Combine rays from a model")
        .long_about(COMBINE_RAYS_FROM_MODEL_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, combine_rays_from_model_fn);
    CmdArgs::add_arg_named_point(&mut build, (None, true));
    build
}

fn add_fn(&mut self) -> CmdResult {
    let mut cip = Cip::default();

    let camera_filename = cmd_args.get_string_arg(0).unwrap();
    let image_filename = cmd_args.get_string_arg(1).unwrap();
    let pms_filename = cmd_args.get_string_arg(2).unwrap();

    let image_filename2 = image_filename.to_owned();

    cip.set_camera_filename(camera_filename);
    let image = Tag::owned(image_filename);
    cip.set_image(image);
    cip.set_image_filename(image_filename);
    cip.set_pms_filename(pms_filename);
    cip.set_camera(cmd_args.camera().clone().into());

    let cip: Rrc<Cip> = cip.into();
    cmd_args.project_mut().add_cip(cip.clone());
    let _ = cmd_args.set_cip(&image_filename2);
    CmdArgs::cmd_ok()
}

fn as_json_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("as_json").about("Generate the JSON for the CIP");

    CommandBuilder::with_handler(command, as_json_fn)
}

fn show_mappings_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("show_mappings")
        .about("Show the total and worst error for a point mapping set");

    let mut build = CommandBuilder::with_handler(command, show_mappings_fn);
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);
    build
}

fn list_cmd() -> CommandBuilder<CmdArgs> {
    let command =
        Command::new("list").about("Show the total and worst error for a point mapping set");

    let mut build = CommandBuilder::with_handler(command, list_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, true));

    build
}
fn add_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("add").about("Add a new CIP");

    let mut build = CommandBuilder::with_handler(command, add_fn);
    CmdArgs::add_arg_positional_string(
        &mut build,
        "camera",
        "Camera filename for the CIP",
        Some(1),
        None,
    );
    CmdArgs::add_arg_positional_string(
        &mut build,
        "image",
        "Image filename for the CIP",
        Some(1),
        None,
    );
    CmdArgs::add_arg_positional_string(
        &mut build,
        "pms",
        "Point mapping set filename for the CIP",
        Some(1),
        None,
    );

    build
}

pub fn cip_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("cip")
        .about("Operate on a camera/image/point mapping set")
        .version("0.1.0");

    let mut build = CommandBuilder::new(command);
    CmdArgs::add_arg_cip(&mut build, false);

    build.add_subcommand(as_json_cmd());
    build.add_subcommand(image_cmd());
    build.add_subcommand(image_patch_cmd());
    build.add_subcommand(show_mappings_cmd());
    build.add_subcommand(list_cmd());
    build.add_subcommand(add_cmd());
    build.add_subcommand(locate_cmd());
    build.add_subcommand(orient_cmd());
    build.add_subcommand(locate_and_orient_cmd());
    build.add_subcommand(relocate_and_orient_cmd());
    build.add_subcommand(create_rays_cmd());
    build.add_subcommand(combine_rays_from_model_cmd());
    build.add_subcommand(show_rays_cmd());

    build
}
*/
