use std::rc::Rc;
use std::{collections::HashMap, num};

use anyhow::anyhow;
use geo_nd::Vector;
use ic_photogram::Color8;
use ic_photogram::ModelData;
use thunderclap::{CmdDescriptor, CommandArgs, json};

use ic_photogram::CameraInstanceProjection;
use ic_photogram::NamedPointSet;
use ic_photogram::{JsonParsable, Point3D, Ray, TagSet};

use crate::cmd::{CmdArgs, CmdResult};

//a Help
//hi COMBINE_RAYS_FROM_MODEL_LONG_HELP
const COMBINE_RAYS_FROM_MODEL_LONG_HELP: &str = "\
This combines a list of from-model rays from a JSON file and generates
a model-space best location of ray intersection.

The rays in the file are from different model points and the direction
thereof should have been generated by casting rays through a camera
frame and applying in reverse the camera orientation.

Real-world rays will not intersect precisely; there will be a point
that has the minimum square distance from all the rays, though. This
is the point generated.

Combining the rays from model produces a Camera JSON result (with an updated
direction, no change to orientation), but does not modify the camera
";

//hi COMBINE_RAYS_FROM_CAMERA_LONG_HELP
const COMBINE_RAYS_FROM_CAMERA_LONG_HELP: &str = "\
This combines a list of named rays from a number of JSON files, and
generates a model-space best location of ray intersections for chosen
names (which correspond to named points, usually)

The rays in each file are from the camera toward named points in model
space, and thereof should have been generated by casting rays from a
camera sensor through the camera, applying its orientation and
starting from the camera's position. Multiple ray files should be
used, generated from different cameras

Real-world rays will not intersect precisely; there will be a point
that has the minimum square distance from all the rays, though. This
is the point generated.

Combine rays from camera produces a new 'named point set' JSON.
";

const GET_MODEL_POINTS_LONG_HELP: &str = "\
This combines camera location and PMS files, using them to determine
model positions for Named Points.

This takes a list of Camera/PMS files, and reads them in.  Then, for
each Named Point in the NPS file read in it calculates one ray from
each camera location in the direction given by the PMS for the ray,
creating N rays for N cameras.

The intersection of these N rays is then determined, yielding a
model-space point for the Named Point.

A new NamedPointSet is generated from the original NPS with these new
model-space points from the ray intersections.";

const PROJECT_LONG_HELP: &str = "\
Project help";

const LIST_LONG_HELP: &str = "\
List the information about one or more named points
";

const ADD_LONG_HELP: &str = "\
Add a named point to the set
";

const UPDATE_MODEL_LONG_HELP: &str = "\
Add and/or update model positions for all named points in the supplied JSON
";

impl CmdArgs {
    fn np_combine_rays_from_model_cmd(&mut self) -> CmdResult {
        let named_rays = self.named_rays();

        let mut names = Vec::new();
        let mut ray_list = Vec::new();
        for (name, ray) in named_rays.iter() {
            names.push(name);
            ray_list.push(*ray);
        }
        if named_rays.len() < 2 {
            return Err(anyhow!(
                "Not enough rays ({}) to combine to generate a position for the camera",
                ray_list.len()
            ));
        }

        let position =
            Ray::closest_point(named_rays.iter().map(|(_, r)| r), &|r| 1.0 / r.tan_error())
                .unwrap();
        eprintln!("The rays from the model converge at the camera focal point at {position}",);

        let mut tot_d_sq = 0.0;
        for (_name, ray) in names.iter().zip(ray_list.iter()) {
            let (_k, d_sq) = ray.distances(&position);
            self.if_verbose(|| {
                eprintln!("{}: k {} dsq {} d {}", _name, _k, d_sq, d_sq.sqrt());
            });
            tot_d_sq += d_sq;
        }

        eprintln!("Total dsq {tot_d_sq}");

        let mut camera = self.camera().clone();
        camera.set_position(&position);
        Ok(json::to_value(camera)?)
    }

    fn np_combine_rays_from_camera_cmd(&mut self) -> CmdResult {
        let nps = self.nps();
        let named_rays = self.named_rays();

        let mut named_point_rays = HashMap::new();
        for (name, ray) in named_rays.iter() {
            if nps.borrow().get_rc_np(name).is_none() {
                eprintln!(
                    "Warning: failed to find point name '{}' in named point set",
                    &name
                );
            } else {
                if !named_point_rays.contains_key(name) {
                    named_point_rays.insert(name.to_owned(), Vec::new());
                }
                named_point_rays.get_mut(name).unwrap().push(*ray);
            }
        }

        let mut k: Vec<String> = named_point_rays.keys().cloned().collect();
        k.sort();
        for name in &k {
            let ray_list = named_point_rays.get(name).unwrap();
            if ray_list.len() > 1 {
                let p = Ray::closest_point(ray_list.iter(), &|r| 1.0 / r.tan_error()).unwrap();
                eprintln!("Point '{name}' - even weight - {p}");
            }
        }

        Ok(json::to_value(named_point_rays)?)
    }

    fn np_get_model_points_cmd(self: &mut CmdArgs) -> CmdResult {
        let nps = self.get_nps()?;

        let cips: Vec<_> = self
            .arg_strings()
            .map(|cip| {
                /* bound it */
                let cip = self
                    .project
                    .find_cip(cip)
                    .expect("Need error - could not find CIP")
                    .borrow();
                (cip.pms().clone(), cip.camera().clone())
            })
            .collect();

        for (_, c) in &cips {
            if c.borrow().position() == Point3D::default() {
                eprintln!(
                    "Warning: CIP had a default position for get_model_points - probably deriving from unlocated camera"
                );
            }
        }

        let mut result_nps = NamedPointSet::default();
        // Don't really need a TagSet as  the named points are single use, but it is good practice
        result_nps.set_tag_set(Rc::new(TagSet::default()));
        for np in nps {
            let mut ray_list = Vec::new();
            let mut cip_of_ray_list = Vec::new();
            for (n, (pms, camera)) in cips.iter().enumerate() {
                if camera.borrow().position().is_zero() {
                    continue;
                }

                // Get a ray only if the CIP maps that named point onto its sensor with a PointMapping
                if let Some(pm) = pms.borrow().mapping_of_np(&np) {
                    let ray = pm.get_mapped_ray(&*camera.borrow(), true);
                    ray_list.push(ray);
                    cip_of_ray_list.push(n);
                }
            }
            if ray_list.len() > 1 {
                if let Some(pt) = Ray::closest_point(ray_list.iter(), &|_r| 1.0) {
                    let e_sq = ray_list
                        .iter()
                        .fold(f64::MAX, |acc, r| acc.min(r.distances(&pt).1));
                    result_nps.add_pt(
                        np.ref_tag().as_str(),
                        np.color(),
                        ModelData::at_infinity(pt).with_uncertainty(e_sq.sqrt()),
                    );
                    self.if_verbose(|| {
                        for (cip_n, r) in cip_of_ray_list.iter().zip(ray_list.iter()) {
                            eprintln!(
                                "Ray to {} {:?} {}",
                                np.ref_tag(),
                                r.distances(&pt),
                                self.get_string_arg(*cip_n).unwrap()
                            );
                        }
                    });
                }
            }
        }
        Ok(json::to_value(result_nps)?)
    }

    fn np_as_json_cmd(self: &mut CmdArgs) -> CmdResult {
        Ok(json::to_value(
            self.nps().borrow().to_json(self.pretty_json())?,
        )?)
    }

    fn np_list_cmd(self: &mut CmdArgs) -> CmdResult {
        let nps = self.get_nps()?;
        for np in nps {
            println!("{np}");
        }
        Ok("".into())
    }

    fn np_add_cmd(self: &mut CmdArgs) -> CmdResult {
        let name = self.get_string_arg(0).unwrap();
        if self.project().nps_ref().get_rc_np(name).is_some() {
            return Err(anyhow!("Named point {name} already exists in the set"));
        }
        let color = self
            .model_color()
            .cloned()
            .unwrap_or_else(|| (255, 255, 0).into());
        if let Some(model) = self.get_point3d(0).cloned() {
            let err = self.max_error();
            self.project().nps_mut().add_pt(
                name,
                color,
                ModelData::at_infinity(model).with_uncertainty(err),
            );
        } else {
            self.project()
                .nps_mut()
                .add_pt(name, color, ModelData::default());
        }

        CmdArgs::cmd_ok()
    }

    fn np_derive_directions_cmd(self: &mut CmdArgs) -> CmdResult {
        let nps = self.get_nps()?;
        let mut cips = vec![];
        for i in 0..self.project.ncips() {
            let cip_name = self.project.cip_name(i).unwrap();
            let cip = self.project.find_cip(cip_name).unwrap();
            cips.push(cip.clone());
        }
        if self.verbose {
            let points: Vec<_> = nps
                .iter()
                .map(|np| np.ref_tag().as_str().to_owned())
                .collect();
            let cips: Vec<_> = cips
                .iter()
                .map(|cip| cip.borrow().name_as_tag().as_str().to_owned())
                .collect();
            eprintln!("Deriving directions for points {points:?} and CIPS {cips:?}");
        }
        for np in nps {
            let mut direction = Point3D::default();
            let mut num_mappings = 0_usize;
            for c in &cips {
                if let Some(pm) = c.borrow().pms().borrow().mapping_of_np(&np) {
                    let pm_direction = pm.get_mapped_world_dir(&*c.borrow().camera_ref());
                    num_mappings += 1;
                    direction += pm_direction;
                    if false {
                        // Check that there-and-back for screen to world direction is basically identical
                        eprintln!(
                            "{:.2} : {:.2}",
                            pm.screen(),
                            c.borrow()
                                .camera_ref()
                                .world_dir_to_opt_px_abs_xy(&pm_direction)
                                .unwrap_or_default()
                        );
                    }
                }
            }
            if num_mappings > 0 {
                direction = direction / (num_mappings as f64);
                if self.verbose {
                    eprintln!(
                        "Set mapping for {} to {:.3} from {num_mappings}",
                        np.ref_tag(),
                        direction
                    );
                }
                *np.model_mut() = ModelData::at_infinity(direction);
            }
        }
        CmdArgs::cmd_ok()
    }

    fn np_update_from_nps_cmd(self: &mut CmdArgs) -> CmdResult {
        let new_nps = NamedPointSet::load_json(self.get_string_arg(0).unwrap(), &())?;
        for opt_new_np in new_nps.into_iter() {
            // All of the named points are unshared, so we can unwrap
            let new_np = opt_new_np.unwrap();
            if let Some(np) = self.nps().borrow().get_rc_np(new_np.ref_tag().as_str()) {
                if new_np.model().is_mapped() {
                    if np.is_unmapped() || np.model_uncertainty() != 0.0 {
                        *np.model_mut() = *new_np.model();
                    }
                }
            } else {
                self.nps().borrow_mut().add_np(new_np);
            }
        }
        CmdArgs::cmd_ok()
    }

    const NP_LIST_CMD: CmdDescriptor<Self> = CmdDescriptor::new("list")
        .about("List information about the named points")
        .args(&[Self::ARG_ADD_NAMED_POINT])
        .handler(&Self::np_list_cmd);

    const NP_AS_JSON_CMD: CmdDescriptor<Self> = CmdDescriptor::new("as_json")
        .about("Generate the JSON for the named points")
        .args(&[])
        .handler(&Self::np_as_json_cmd);

    const NP_ADD_CMD: CmdDescriptor<Self> = CmdDescriptor::new("add")
        .about("Add a named point to the set for the project")
        .args(&[
            Self::ARG_POSITIONAL_NAME,
            Self::ARG_MODEL_COLOR,
            Self::ARG_MAX_ERROR,
        ])
        .handler(&Self::np_add_cmd);

    const NP_DERIVE_DIRECTIONS_CMD: CmdDescriptor<Self> = CmdDescriptor::new("derive_directions")
        .about("Derive directions (not positions) for all the named points in the filter using all CIPs")
        .args(&[
            Self::ARG_ADD_NAMED_POINT,
        ])
        .handler(&Self::np_derive_directions_cmd);

    /*    const NP_UPDATE_FROM_NPS_CMD: CmdDescriptor<Self> = CmdDescriptor::new("update_from_nps")
    .about("Update all entries from a supplied NPS JSON")
    .args(&[Self::ARG_STRING])
    .handler(&Self::np_update_from_nps_cmd);
    */

    pub(crate) const NAMED_POINTS_CMD: CmdDescriptor<Self> = CmdDescriptor::new("nps")
        .about("List, modify, interrogate etc a set of 'NamedPoints'")
        .long_about(PROJECT_LONG_HELP)
        .args(&[])
        .cmds(&[
            Self::NP_LIST_CMD,
            Self::NP_ADD_CMD,
            Self::NP_AS_JSON_CMD,
            Self::NP_DERIVE_DIRECTIONS_CMD,
            /*
            Self::NP_UPDATE_FROM_NPS_CMD,
                         Self::NP_GET_MODEL_POINTS_CMD,
            Self::NP_COMBINE_RAYS_FROM_MODEL_CMD,
            Self::NP_COMBINE_RAYS_FROM_CAMERA_CMD,
            */
        ]);
}
/*

    CmdArgs::add_arg_positional_string(
        &mut build,
        "json",
        "Named point set JSON to update with",
        Some(1),
        None,
    );

    build
}

fn combine_rays_from_model_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("combine_rays_from_model")
        .about("Combine rays from a model")
        .long_about(COMBINE_RAYS_FROM_MODEL_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, combine_rays_from_model_fn);
    CmdArgs::add_arg_named_ray_file(&mut build, (1,));
    build
}

fn combine_rays_from_camera_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("combine_rays_from_camera")
        .about("Combine rays from a camera")
        .long_about(COMBINE_RAYS_FROM_CAMERA_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, combine_rays_from_camera_fn);
    CmdArgs::add_arg_named_ray_file(&mut build, (1,));

    build
}

fn get_model_points_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("get_model_points")
        .about("Get model points from camera and pms")
        .long_about(GET_MODEL_POINTS_LONG_HELP);

    let mut build = CommandBuilder::with_handler(command, get_model_points_fn);

    CmdArgs::add_arg_named_point(&mut build, (None, false));

    CmdArgs::add_arg_positional_string(
        &mut build,
        "cip",
        "Cip names to use for the point mappings",
        None,
        None,
    );

    build
}
*/
