use std::{collections::HashMap, path::PathBuf};

use serde::{Deserialize, Serialize};

use ic_base::{PathSet, Result};
use ic_image::{ImageGray16, ImageRgb8, ImageSquareSet, read_image};

/// A description that is serializable/deserializable from which the
/// ImageSquareSets can be read
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct ImageSquareSetsDesc {
    /// Map from name to filename
    #[serde(flatten)]
    index: HashMap<String, String>,
}

/// The sets of ImageSquareSet, that are images that contain many
/// fragments of (transformed) source squares.
///
/// Ultimately a fragment might have come from an image directly, but
/// usually it is from some mapping generated by a patch
#[derive(Debug, Default)]
pub struct ImageSquareSets {
    /// Map from name to filename
    index: HashMap<String, String>,
    rgb: Vec<ImageSquareSet<ImageRgb8>>,
    rgb_index: HashMap<String, usize>,
    gray: Vec<ImageSquareSet<ImageGray16>>,
    gray_index: HashMap<String, usize>,
}

impl Serialize for ImageSquareSets {
    fn serialize<S>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let desc = ImageSquareSetsDesc {
            index: self.index.clone(),
        };
        desc.serialize(serializer)
    }
}

impl ImageSquareSets {
    //cp from_desc
    pub fn from_desc(desc: ImageSquareSetsDesc) -> Self {
        Self {
            index: desc.index,
            ..Default::default()
        }
    }

    pub fn ensure_loaded(&mut self, path_set: &PathSet) -> Result<()> {
        let name_filenames: Vec<_> = self
            .index
            .iter()
            .map(|(a, b)| (a.clone(), b.clone()))
            .collect();
        for (name, filename) in name_filenames {
            if self.rgb_index.contains_key(&name) {
                continue;
            }
            if self.gray_index.contains_key(&name) {
                continue;
            }
            self.load_file(path_set, &filename, &name)?;
        }
        Ok(())
    }

    pub fn load_file(&mut self, path_set: &PathSet, path: &str, name: &str) -> Result<()> {
        let (filename, opt_rgb, opt_gray) = read_image(path_set, path)?;
        if let Some(rgb) = opt_rgb {
            self.add_rgb(name, filename, ImageSquareSet::create(rgb, 8)?);
        } else if let Some(gray) = opt_gray {
            self.add_gray(name, filename, ImageSquareSet::create(gray, 8)?);
        }
        Ok(())
    }

    pub fn add_rgb(
        &mut self,
        name: &str,
        filename: PathBuf,
        mut img: ImageSquareSet<ImageRgb8>,
    ) -> usize {
        let n = self.rgb.len();
        img.set_image_filename(filename);
        self.rgb.push(img);
        self.rgb_index.insert(name.into(), n);
        n
    }

    pub fn add_gray(
        &mut self,
        name: &str,
        filename: PathBuf,
        mut img: ImageSquareSet<ImageGray16>,
    ) -> usize {
        let n = self.gray.len();
        img.set_image_filename(filename);
        self.gray.push(img);
        self.gray_index.insert(name.into(), n);
        n
    }
}
