//a Imports
use std::collections::HashMap;

use clap::Command;

use thunderclap::CommandBuilder;

use ic_base::{Ray, Result};
use ic_camera::CameraProjection;
use ic_image::{Color, Image, Patch, Region};
use ic_mapping::{
    CameraAdjustMapping, CameraPtMapping, CameraShowMapping, ModelLineSet, NamedPointSet,
    PointMappingSet,
};

//a Help
//hi IMAGE_LONG_HELP
const IMAGE_LONG_HELP: &str = "\
Given a Named Point Set, from a camera (type, position/direction), and
a Point Mapping Set draw crosses on an image corresponding to the PMS
frame positions and the Named Point's model position mapped onto the
camera, and write out to a new image.

";

//hi IMAGE_PATCH_LONG_HELP
const IMAGE_PATCH_LONG_HELP: &str = "\
Extract a triangular patch from an image as if viewed straight on

";

//hi GET_POINT_MAPPINGS_LONG_HELP
const GET_POINT_MAPPINGS_LONG_HELP: &str = "\
This treats the image file read in as a set of non-background color
regions each of which should be of a color representing a Named Point

A region is a contiguous set of non-background pixels. The
centre-of-gravity of each region is determined.

The Named Point associated with the color of the region is found, and
a Point Mapping Set is generated mapping the Named Points onto the
centre of the appropriate region.";

//hi ORIENT_LONG_HELP
const ORIENT_LONG_HELP: &str = "\
Use consecutive pairs of point mappings to determine a camera
orientation, and average them.

*An* orientation is generated to rotate the first of each pair of
point mappings to the Z axis from its screen direction, and from its
to-model direction; these are applied to the second points in the
pairs, and then a rotation around the Z axis to map on onto the other
(assumming the angle they subtend is the same!) is generated. This
yields three quaternions which are combined to generate an orientation
of the camera.

The orientations from each pair of point mappings should be identical;
an average is generated, and the camera orientation set to this.

";

//hi REORIENT_LONG_HELP
const REORIENT_LONG_HELP: &str = "\
Iteratively reorient the camera by determining the axis and amount *each* PMS
mapped point wants to rotate by, and rotating by the weighted
average.

The rotation desired for a PMS point is the axis/angle required to
rotate the ray vector from the camera through the point on the frame
to the ray of the *actual* model position of the point from the
camera.

The weighted average is biased by adding in some 'zero rotation's; the
camera is attempted to be rotated by this weighted average
(quaternion), and if the total error in the camera mapping is reduced
then the new rotation is kept.

The iteration stops when the new rotation produces a greater total
error in the mapping than the current orientation of the camera.

";

//hi COMBINE_RAYS_FROM_MODEL_LONG_HELP
const COMBINE_RAYS_FROM_MODEL_LONG_HELP: &str = "\
This combines a list of rays from a JSON file and generates 
a model-space best location of ray intersection.

The rays in the file are from different model points and the direction
thereof should have been generated by casting rays through a camera
frame and applying in reverse the camera orientation.

Real-world rays will not intersect precisely; there will be a point
that has the minimum square distance from all the rays, though. This
is the point generated.

";

//hi CREATE_RAYS_FROM_MODEL_LONG_HELP
const CREATE_RAYS_FROM_MODEL_LONG_HELP: &str = "\
This combines Named Point model positions, camera *orientation* and
PMS files, to determine rays from those model positions.

This takes the Point Mapping Set and a camera description and uses
only the orientation from that description.

For each Named Point that is mapped it casts a ray from the camera
through the frame to generate the direction of rays *relative* to the
camera orientation, then it applies the inverse camera rotation to get
the real world direction of the ray.

Given the Named Point's model position and world direction, it has a
Model-space ray for the named point.
";

//hi GET_MODEL_POINTS_LONG_HELP
const GET_MODEL_POINTS_LONG_HELP: &str = "\
This combines camera location and PMS files, using them to determine
model positions for Named Points.

This takes a list of Camera/PMS files, and reads them in.  Then, for
each Named Point in the NPS file read in it calculates one ray from
each camera location in the direction given by the PMS for the ray,
creating N rays for N cameras.

The intersection of these N rays is then determined, yielding a
model-space point for the Named Point.

A new NamedPointSet is generated from the original NPS with these new
model-space points from the ray intersections.";

//hi PROJECT_LONG_HELP
const PROJECT_LONG_HELP: &str = "\
Project help";

//a Stuff
use ic_cmdline::{CmdArgs, CmdResult};

//a Images
//fi image_cmd
fn image_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("image")
        .about("Read image and draw crosses on named and mapped points")
        .long_about(IMAGE_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(image_fn)));
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);
    CmdArgs::add_arg_read_image(&mut build, Some(1_usize).into()); // 0 or 1 in  alist
    CmdArgs::add_arg_write_image(&mut build, true);
    CmdArgs::add_arg_pms_color(&mut build);
    CmdArgs::add_arg_model_color(&mut build);
    build
}

//fi image_fn
fn image_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let pms_color = cmd_args.pms_color();
    let model_color = cmd_args.model_color();
    let use_nps_colors = cmd_args.pms_color().is_none() && cmd_args.model_color().is_none();

    let write_filename = cmd_args.write_img().unwrap();

    let mut img = cmd_args.get_image_read_or_create()?;

    let c = [255, 255, 255, 255].into();
    let cn = [255, 190, 190, 255].into();
    let camera = cmd_args.camera();
    for i in 0_usize..200 {
        let xyz = (i as f64) * 1.0;
        let sz = {
            if i.is_multiple_of(10) {
                3.0
            } else if i.is_multiple_of(5) {
                2.0
            } else {
                1.0
            }
        };
        let mapped = camera.map_model([xyz, 0., 0.].into());
        img.draw_cross(mapped, sz, &c);
        let mapped = camera.map_model([0., xyz, 0.].into());
        img.draw_cross(mapped, sz, &c);
        let mapped = camera.map_model([0., 0., xyz].into());
        img.draw_cross(mapped, sz, &c);

        let mapped = camera.map_model([-xyz, 0., 0.].into());
        img.draw_cross(mapped, sz, &cn);
        let mapped = camera.map_model([0., -xyz, 0.].into());
        img.draw_cross(mapped, sz, &cn);
        let mapped = camera.map_model([0., 0., -xyz].into());
        img.draw_cross(mapped, sz, &cn);
    }

    if pms_color.is_some() || use_nps_colors {
        cmd_args.pms_map(|pms| {
            let mappings = pms.mappings();
            for m in mappings {
                let c = pms_color.unwrap_or(m.model.color());
                img.draw_cross(m.screen(), m.error(), c);
            }
            Ok(())
        })?;
    }
    if model_color.is_some() || use_nps_colors {
        let camera = cmd_args.camera();
        let nps = cmd_args.nps();
        for (_name, p) in nps.iter() {
            let c = model_color.unwrap_or(p.color());
            let xyz = p.model().0;
            let n = ((xyz[2] * 2.0).abs().floor() as usize);
            let dz = xyz[2].signum() / 2.0;
            for z in 0..n {
                let sz = {
                    if z.is_multiple_of(10) {
                        3.0
                    } else if z.is_multiple_of(5) {
                        2.0
                    } else {
                        1.0
                    }
                };
                let xyz = [xyz[0], xyz[1], (z as f64) * dz];
                let mapped = camera.map_model(xyz.into());
                img.draw_cross(mapped, sz, c);
            }
            if xyz[0].abs() < xyz[1].abs() {
                let n = ((xyz[0] * 2.0).abs().floor() as usize);
                let dx = xyz[0].signum() / 2.0;
                for x in 0..n {
                    let sz = {
                        if x.is_multiple_of(10) {
                            3.0
                        } else if x.is_multiple_of(5) {
                            2.0
                        } else {
                            1.0
                        }
                    };
                    let xyz = [(x as f64) * dx, xyz[1], 0.];
                    let mapped = camera.map_model(xyz.into());
                    img.draw_cross(mapped, sz, c);
                }
            } else {
                let n = ((xyz[1] * 2.0).abs().floor() as usize);
                let dy = xyz[1].signum() / 2.0;
                for y in 0..n {
                    let sz = {
                        if y.is_multiple_of(10) {
                            3.0
                        } else if y.is_multiple_of(5) {
                            2.0
                        } else {
                            1.0
                        }
                    };
                    let xyz = [xyz[0], (y as f64) * dy, 0.];
                    let mapped = camera.map_model(xyz.into());
                    img.draw_cross(mapped, sz, c);
                }
            }
            let mapped = camera.map_model(xyz);
            img.draw_cross(mapped, 5.0, c);
        }
    }
    img.write(write_filename)?;
    Ok("".into())
}

//fi image_patch_cmd
fn image_patch_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("image_patch")
        .about("Extract a patch from an image")
        .long_about(IMAGE_PATCH_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(image_patch_fn)));

    // let cmd = cmdline_args::add_image_dir_arg(cmd, false);
    CmdArgs::add_arg_cip(&mut build, false);
    CmdArgs::add_arg_read_image(&mut build, 1_usize.into());
    CmdArgs::add_arg_write_image(&mut build, true);
    CmdArgs::add_arg_named_point(&mut build, (3,).into());
    build
}

//fi image_patch_fn
fn image_patch_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let nps = cmd_args.nps();
    let cip = cmd_args.cip().borrow();
    let camera = cip.camera_ref();
    let src_img = cmd_args.get_image_read_or_create()?;
    let write_filename = cmd_args.write_img().unwrap();

    let mut model_pts = vec![];
    for name in cmd_args.np_names() {
        if let Some(n) = nps.get_pt(name) {
            let model = n.model().0;
            model_pts.push((name, model, camera.map_model(model)))
        } else {
            return Err(format!("Could not find NP {name} in the project").into());
        }
    }
    if model_pts.len() < 3 {
        return Err(format!(
            "Need at least 3 points for a patch, got {}",
            model_pts.len()
        )
        .into());
    }

    for m in &model_pts {
        println!("{} {} {}", m.0, m.1, m.2);
    }
    let model_pts: Vec<_> = model_pts.into_iter().map(|(_, m, _)| m).collect();

    if let Some(patch) = Patch::create(&src_img, 10.0, &model_pts, &|m| camera.map_model(m))? {
        patch.img().write(write_filename)?;
    }
    Ok("".into())
}

//a Interrogate (show_mappings etc)
//fi show_mappings_cmd
fn show_mappings_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("show_mappings")
        .about("Show the total and worst error for a point mapping set");

    let mut build = CommandBuilder::new(command, Some(Box::new(show_mappings_fn)));
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);
    build
}

//fi show_mappings_fn
fn show_mappings_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let pms = cmd_args.pms();
    let nps = cmd_args.nps();
    let camera = cmd_args.camera();
    let mappings = pms.mappings();

    let te = camera.total_error(mappings);
    let we = camera.worst_error(mappings);
    camera.show_mappings(mappings);
    camera.show_point_set(&nps);
    println!("WE {we:.2} TE {te:.2}");

    Ok("".into())
}

//a Get point mappings
//fi get_point_mappings_cmd
fn get_point_mappings_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("get_point_mappings")
        .about("Read image and find regions")
        .long_about(GET_POINT_MAPPINGS_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(get_point_mappings_fn)));
    CmdArgs::add_arg_read_image(&mut build, true.into());
    CmdArgs::add_arg_bg_color(&mut build);
    build
}

//fi get_point_mappings_fn
fn get_point_mappings_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let nps = cmd_args.nps();
    let img = cmd_args.get_image_read_or_create()?;
    let bg_color = cmd_args.bg_color().copied().unwrap_or(Color::black());

    let regions = Region::regions_of_image(&img, &|c| !c.color_eq(&bg_color), &|c0, c1| {
        (c0.brightness() - c1.brightness()).abs() < 0.1
    });
    let mut pms = PointMappingSet::default();
    for r in regions {
        let c = r.color();
        let np = nps.of_color(&c);
        if np.is_empty() {
            eprintln!("No named point with color {c} @ {:?}", r.cog());
        } else if np.len() > 1 {
            eprintln!(
                "More than one named point with color {c} @ {:?}: {}, {}, ...",
                r.cog(),
                np[0].name(),
                np[1].name(),
            );
        } else {
            let screen = r.cog();
            let screen = [screen.0, screen.1].into();
            let error = r.spread();
            pms.add_mapping(&nps, np[0].name(), &screen, error);
        }
    }
    println!("{}", serde_json::to_string_pretty(&pms).unwrap());
    cmd_args.if_verbose(|| {
        eprintln!("Exported {} mappings", pms.mappings().len());
    });
    Ok("".into())
}

//a Locate
//fi locate_cmd
fn locate_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("locate")
        .about("Find location and orientation for a camera to map points to model");

    let mut build = CommandBuilder::new(command, Some(Box::new(locate_fn)));
    CmdArgs::add_arg_cip(&mut build, false.into());
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);
    CmdArgs::add_arg_write_camera(&mut build);
    build
}

//fi locate_fn
fn locate_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let mut mls = ModelLineSet::new(cmd_args.camera().clone());
    cmd_args.pms_map(|pms| {
        let mappings = pms.mappings();
        let n = pms.mappings().len();
        if n < 3 {
            Err(format!("Required at least 3 mapped points, but found {n}",).into())
        } else if n < 6 {
            for i in 0..n {
                for j in (i + 1)..n {
                    mls.add_line((&mappings[i], &mappings[j]));
                }
            }
            Ok(())
        } else {
            for (i, j) in pms.get_good_screen_pairs(&|_f| true) {
                mls.add_line((&mappings[i], &mappings[j]));
            }
            Ok(())
        }
    })?;
    if mls.num_lines() < 2 {
        return Err(format!(
            "Required at least 2 good screen pairs, but found {}",
            mls.num_lines()
        )
        .into());
    }
    cmd_args.if_verbose(|| {
        eprintln!("Using {} model lines", mls.num_lines());
    });
    // let (location, err) = mls.find_best_min_err_location(&|p| p[0] < 0., 1000, 1000);
    let (location, err) = mls.find_best_min_err_location(&|_| true, 1000, 1000);

    cmd_args.camera_mut().set_position(location);
    cmd_args.if_verbose(|| {
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs();
    cmd_args.output_camera()
}

//a orient / reorient
//fi orient_cmd
fn orient_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("orient")
        .about("Set the orientation for a camera using weighted average of pairs of point mappings")
        .long_about(ORIENT_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(orient_fn)));
    CmdArgs::add_arg_cip(&mut build, false.into());
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);
    CmdArgs::add_arg_write_camera(&mut build);
    build
}

//fi orient_fn
fn orient_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let mut camera = cmd_args.camera().clone();
    cmd_args.pms_map(|pms| {
        camera.orient_using_rays_from_model(pms.mappings());
        Ok(())
    })?;

    cmd_args.camera_mut().set_orientation(camera.orientation());

    cmd_args.if_verbose(|| {
        eprintln!("{}", cmd_args.camera());
    });
    cmd_args.write_outputs();
    cmd_args.output_camera()
}

//fi reorient_cmd
fn reorient_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("reorient")
        .about("Improve orientation for a camera to map points to model")
        .long_about(REORIENT_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(reorient_fn)));
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, true); // required=true
    build
}

//fi reorient_fn
fn reorient_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let pms = cmd_args.pms();
    let mut camera = cmd_args.camera().clone();

    camera.reorient_using_rays_from_model(pms.mappings());
    *cmd_args.camera_mut() = camera;
    let camera = cmd_args.camera();

    println!("{}", serde_json::to_string_pretty(&camera).unwrap());
    Ok("".into())
}

//a CombineFrom
//fi combine_rays_from_model_cmd
fn combine_rays_from_model_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("combine_rays_from_model")
        .about("Combine rays from a model")
        .long_about(COMBINE_RAYS_FROM_MODEL_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(combine_rays_from_model_fn)));
    CmdArgs::add_arg_camera(&mut build, false); // required=true
    CmdArgs::add_arg_ray_file(&mut build, (1,).into());
    build
}

//fi combine_rays_from_model_fn
fn combine_rays_from_model_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let nps = cmd_args.nps();
    let named_rays = cmd_args.named_rays();

    let mut names = Vec::new();
    let mut ray_list = Vec::new();
    for (name, ray) in named_rays {
        names.push(name);
        ray_list.push(*ray);
    }
    if ray_list.len() <= 1 {
        return Err(format!(
            "Not enough rays ({}) to combine to generate a position for the camera",
            ray_list.len()
        )
        .into());
    }

    let position = Ray::closest_point(&ray_list, &|r| 1.0 / r.tan_error()).unwrap();
    eprintln!("The rays from the model converge at the camera focal point at {position}",);

    let mut tot_d_sq = 0.0;
    for (_name, ray) in names.iter().zip(ray_list.iter()) {
        let (_k, d_sq) = ray.distances(&position);
        cmd_args.if_verbose(|| {
            eprintln!("{}: k {} dsq {} d {}", _name, _k, d_sq, d_sq.sqrt());
        });
        tot_d_sq += d_sq;
    }

    drop(named_rays);
    drop(nps);
    eprintln!("Total dsq {tot_d_sq}");

    cmd_args.camera_mut().set_position(position);
    let camera = cmd_args.camera();
    println!("{}", serde_json::to_string_pretty(&camera).unwrap());
    Ok("".into())
}

//fi combine_rays_from_camera_cmd
fn combine_rays_from_camera_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("combine_rays_from_camera").about("Combine rays from a camera");

    let mut build = CommandBuilder::new(command, Some(Box::new(combine_rays_from_camera_fn)));
    CmdArgs::add_arg_ray_file(&mut build, (1,).into());

    build
}

//fi combine_rays_from_camera_fn
fn combine_rays_from_camera_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let nps = cmd_args.nps();
    let named_rays = cmd_args.named_rays();

    let mut named_point_rays = HashMap::new();
    for (name, ray) in named_rays {
        if nps.get_pt(&name).is_none() {
            eprintln!(
                "Warning: failed to find point name '{}' in named point set",
                &name
            );
        } else {
            if !named_point_rays.contains_key(name) {
                named_point_rays.insert(name.to_owned(), Vec::new());
            }
            named_point_rays.get_mut(name).unwrap().push(*ray);
        }
    }

    let mut k: Vec<String> = named_point_rays.keys().cloned().collect();
    k.sort();
    for name in &k {
        let ray_list = named_point_rays.get(name).unwrap();
        if ray_list.len() > 1 {
            let p = Ray::closest_point(ray_list, &|r| 1.0 / r.tan_error()).unwrap();
            eprintln!("Point '{name}' - even weight - {p}");
        }
    }

    Ok("".into())
}

//a Create Rays
//fi create_rays_from_model_cmd
fn create_rays_from_model_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("create_rays_from_model")
        .about("Create rays for a given located camera and its mappings")
        .long_about(CREATE_RAYS_FROM_MODEL_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(create_rays_from_model_fn)));
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);

    build
}

//fi create_rays_from_model_fn
fn create_rays_from_model_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let pms = cmd_args.pms();
    let camera = cmd_args.camera();

    let mappings = pms.mappings();

    let named_rays = camera.get_rays(mappings, false);

    cmd_args.if_verbose(|| {
        for (n, r) in &named_rays {
            let end = r.start + r.direction * 400.0;
            eprintln!("{n} {end}");
        }
    });

    println!("{}", serde_json::to_string_pretty(&named_rays).unwrap());
    Ok("".into())
}

//fi create_rays_from_camera_cmd
fn create_rays_from_camera_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("create_rays_from_camera")
        .about("Create rays for a given located camera and its mappings");

    let mut build = CommandBuilder::new(command, Some(Box::new(create_rays_from_camera_fn)));
    CmdArgs::add_arg_pms(&mut build);
    CmdArgs::add_arg_camera(&mut build, false);

    build
}

//fi create_rays_from_camera_fn
fn create_rays_from_camera_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let pms = cmd_args.pms();
    let camera = cmd_args.camera();

    let mappings = pms.mappings();

    println!(
        "{}",
        serde_json::to_string_pretty(&camera.get_rays(mappings, true)).unwrap()
    );
    Ok("".into())
}

//a Get model points
//fi get_model_points_cmd
fn get_model_points_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("get_model_points")
        .about("Get model points from camera and pms")
        .long_about(GET_MODEL_POINTS_LONG_HELP);

    let mut build = CommandBuilder::new(command, Some(Box::new(get_model_points_fn)));
    CmdArgs::add_arg_pms(&mut build); // used to be positional

    build
}

//fi get_model_points_fn
fn get_model_points_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    // let pms = cmd_args.pms();
    let nps = cmd_args.nps();

    //
    let camera_pms: Vec<(ic_camera::CameraInstance, PointMappingSet)> = vec![]; //

    // was camera JSON, PMS json pairs
    // cmdline_args::mapping::get_camera_pms(matches, &base_args.cdb(), &base_args.nps())?;

    let mut result_nps = NamedPointSet::default();
    for (name, np) in nps.iter() {
        let mut ray_list = Vec::new();
        for (camera, pms) in camera_pms.iter() {
            if let Some(pm) = pms.mapping_of_np(np) {
                let ray = camera.get_pm_as_ray(pm, true);
                ray_list.push(ray);
            }
        }
        if ray_list.len() > 1 {
            if let Some(pt) = Ray::closest_point(&ray_list, &|_r| 1.0) {
                let e_sq = ray_list
                    .iter()
                    .fold(f64::MAX, |acc, r| acc.min(r.distances(&pt).1));
                result_nps.add_pt(name, *np.color(), Some(pt), e_sq.sqrt());
                cmd_args.if_verbose(|| {
                    for r in ray_list {
                        eprintln!("Ray to {name} {:?}", r.distances(&pt));
                    }
                });
            }
        }
    }
    println!("{}", serde_json::to_string_pretty(&result_nps).unwrap());
    Ok("".into())
}

//a Project as a whole
//fi project_cmd
fn project_cmd() -> CommandBuilder<CmdArgs> {
    let command = Command::new("project")
        .about("Get model points from camera and pms")
        .long_about(PROJECT_LONG_HELP);

    CommandBuilder::new(command, Some(Box::new(project_fn)))
}

//fi project_fn
fn project_fn(cmd_args: &mut CmdArgs) -> CmdResult {
    let camera = cmd_args.project().cip(0).borrow().camera().clone();

    eprintln!("Camera {camera:?}");
    eprintln!("Mapping {}", camera.borrow().map_model([0., 0., 0.].into()));
    println!(
        "{}",
        serde_json::to_string_pretty(cmd_args.project()).unwrap()
    );
    Ok("".into())
}

//a Main
//fi main
fn main() -> Result<()> {
    let command = Command::new("image_calibrate")
        .about("Image calibration tool")
        .version("0.1.0");

    let mut build = CommandBuilder::new(command, None);

    // build.set_arg_reset(Box::new(CmdArgs::reset_args));

    CmdArgs::add_arg_verbose(&mut build);

    // project must come first, as nps would *add* to it
    CmdArgs::add_arg_project(&mut build, false);

    CmdArgs::add_arg_nps(&mut build);
    CmdArgs::add_arg_camera_database(&mut build, false);

    build.add_subcommand(image_cmd());
    build.add_subcommand(image_patch_cmd());
    build.add_subcommand(show_mappings_cmd());
    build.add_subcommand(get_point_mappings_cmd());
    build.add_subcommand(locate_cmd());
    build.add_subcommand(orient_cmd());
    build.add_subcommand(reorient_cmd());
    build.add_subcommand(combine_rays_from_model_cmd());
    build.add_subcommand(combine_rays_from_camera_cmd());
    build.add_subcommand(create_rays_from_model_cmd());
    build.add_subcommand(create_rays_from_camera_cmd());
    build.add_subcommand(get_model_points_cmd());
    build.add_subcommand(project_cmd());

    let mut cmd_args = CmdArgs::default();
    let mut command = build.main(true, true);
    command.execute_env(&mut cmd_args)?;
    Ok(())
}
